# Generated by Django 4.2.2 on 2023-10-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('description_short', models.TextField()),
                ('description_long', models.TextField()),
                ('coordinates', models.JSONField()),
            ],
        ),
    ]
