# Generated by Django 4.2.2 on 2023-10-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='img',
        ),
    ]
