# Generated by Django 4.2.2 on 2023-10-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_image_delete_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
