# Generated by Django 4.2.2 on 2023-10-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_image_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
